import type { ColumnType } from "kysely";
export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;
export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type AuditLog = {
    id: Generated<number>;
    user_id: number | null;
    action_type: string;
    target_type: string;
    target_id: number | null;
    before_json: unknown | null;
    after_json: unknown | null;
    ip_address: string | null;
    created_at: Generated<Timestamp>;
};
export type Beach = {
    id: Generated<number>;
    name: string;
    region: string;
    lat: string;
    lng: string;
    facing_direction: number | null;
    priority: Generated<number>;
    vulnerability_score: Generated<number>;
    /**
     * 해변 대표 사진 URL. 미등록이면 null → 프론트가 placeholder 로 대체한다.
     */
    image_url: string | null;
    is_active: Generated<number>;
    created_at: Generated<Timestamp>;
    updated_at: Timestamp;
};
export type ConsentLog = {
    id: Generated<number>;
    user_id: number | null;
    user_token: string | null;
    consent_type: string;
    agreed: number;
    policy_version: string;
    agreed_at: Generated<Timestamp>;
    ip_address: string | null;
    expires_at: Timestamp | null;
};
export type DailyReport = {
    id: Generated<number>;
    beach_id: number;
    report_date: Timestamp;
    summary_json: unknown | null;
    max_risk_level: string | null;
    risk_change_summary: string | null;
    report_count: Generated<number>;
    toxic_count: Generated<number>;
    sting_count: Generated<number>;
    action_count: Generated<number>;
    memo: string | null;
    created_by: number | null;
    created_at: Generated<Timestamp>;
    updated_at: Timestamp;
};
export type DataSource = {
    id: Generated<number>;
    source_code: string;
    name: string;
    provider: string | null;
    source_type: string;
    endpoint_url: string | null;
    is_sample: Generated<number>;
    sync_interval_minutes: number | null;
    last_synced_at: Timestamp | null;
    last_sync_status: string | null;
    last_sync_message: string | null;
    is_active: Generated<number>;
    created_at: Generated<Timestamp>;
    updated_at: Timestamp;
};
export type FavoriteBeach = {
    id: Generated<number>;
    user_id: number | null;
    user_token: string | null;
    beach_id: number;
    created_at: Generated<Timestamp>;
};
export type JellyfishOccurrence = {
    id: Generated<number>;
    source_id: number;
    external_id: string | null;
    occurred_at: Timestamp;
    region: string | null;
    lat: string | null;
    lng: string | null;
    species: string | null;
    is_toxic: number | null;
    density_level: string | null;
    alert_level: string | null;
    description: string | null;
    collected_at: Generated<Timestamp>;
};
export type JellyfishReport = {
    id: Generated<number>;
    beach_id: number | null;
    reporter_user_id: number | null;
    reporter_token: string | null;
    lat: string | null;
    lng: string | null;
    image_url: string;
    thumbnail_url: string | null;
    report_type: string;
    status: Generated<string>;
    ai_result: string | null;
    ai_confidence: string | null;
    duplicate_of_report_id: number | null;
    occurred_at: Timestamp;
    submitted_at: Generated<Timestamp>;
    reflected_at: Timestamp | null;
    purge_scheduled_at: Timestamp | null;
};
export type MlModel = {
    id: Generated<number>;
    model_name: string;
    version: string;
    algorithm: string | null;
    model_purpose: string;
    hyperparams_json: unknown | null;
    metrics_json: unknown | null;
    artifact_uri: string | null;
    model_status: Generated<string>;
    trained_at: Timestamp | null;
    activated_at: Timestamp | null;
    created_at: Generated<Timestamp>;
};
export type Notification = {
    id: Generated<number>;
    target_type: string;
    target_user_id: number | null;
    target_user_token: string | null;
    beach_id: number;
    risk_level: string | null;
    event_type: string;
    template_id: number | null;
    title: string | null;
    message: string;
    dedup_key: string | null;
    cooldown_until: Timestamp | null;
    created_at: Generated<Timestamp>;
    read_at: Timestamp | null;
};
export type NotificationConsent = {
    id: Generated<number>;
    user_id: number | null;
    user_token: string | null;
    channel: string;
    agreed: Generated<number>;
    phone_number: string | null;
    device_token: string | null;
    agreed_at: Timestamp | null;
    revoked_at: Timestamp | null;
};
export type NotificationDispatch = {
    id: Generated<number>;
    notification_id: number;
    channel: string;
    provider: string | null;
    recipient: string;
    dispatch_status: Generated<string>;
    failed_reason: string | null;
    retry_count: Generated<number>;
    cost_amount: string | null;
    sent_at: Timestamp | null;
    created_at: Generated<Timestamp>;
};
export type NotificationTemplate = {
    id: Generated<number>;
    template_code: string;
    target_type: string;
    risk_level: string | null;
    event_type: string | null;
    title: string | null;
    body: string;
    active: Generated<number>;
    created_at: Generated<Timestamp>;
    updated_at: Timestamp;
};
export type Observation = {
    id: Generated<number>;
    station_id: number;
    observed_at: Timestamp;
    water_temp: string | null;
    salinity: string | null;
    wave_height: string | null;
    current_direction: number | null;
    current_speed: string | null;
    wind_direction: number | null;
    wind_speed: string | null;
    air_temp: string | null;
    precipitation: string | null;
    quality_flag: Generated<string>;
    collected_at: Generated<Timestamp>;
};
export type ObservationMapping = {
    id: Generated<number>;
    beach_id: number;
    station_id: number;
    station_type: string;
    distance_km: string | null;
    is_primary: number | null;
    created_at: Generated<Timestamp>;
};
export type ObservationStation = {
    id: Generated<number>;
    source_id: number;
    station_code: string;
    name: string;
    station_type: string;
    lat: string;
    lng: string;
    is_active: Generated<number>;
    created_at: Generated<Timestamp>;
};
export type OperationAction = {
    id: Generated<number>;
    beach_id: number;
    risk_score_id: number | null;
    recommendation_id: number | null;
    action_type: string | null;
    operation_status: string;
    memo: string | null;
    created_by: number;
    created_at: Generated<Timestamp>;
};
export type OperationStatusLog = {
    id: Generated<number>;
    beach_id: number;
    operation_action_id: number | null;
    previous_status: string | null;
    new_status: string;
    reason: string | null;
    changed_by: number;
    changed_at: Generated<Timestamp>;
};
export type Partner = {
    id: Generated<number>;
    partner_code: string;
    name: string;
    business_no: string | null;
    contact_name: string | null;
    contact_email: string | null;
    plan_code: string | null;
    partner_status: Generated<string>;
    created_at: Generated<Timestamp>;
};
export type PartnerApiCallLog = {
    id: Generated<number>;
    partner_id: number;
    api_key_id: number | null;
    endpoint: string;
    http_method: string;
    status_code: number;
    response_time_ms: number | null;
    is_billable: Generated<number>;
    called_at: Generated<Timestamp>;
};
export type PartnerApiKey = {
    id: Generated<number>;
    partner_id: number;
    key_prefix: string;
    api_key_hash: string;
    scopes_json: unknown | null;
    rate_limit_per_min: number | null;
    expires_at: Timestamp | null;
    revoked_at: Timestamp | null;
    created_at: Generated<Timestamp>;
};
export type ReportConsent = {
    id: Generated<number>;
    report_id: number;
    consent_log_id: number;
    created_at: Generated<Timestamp>;
};
export type ReportReview = {
    id: Generated<number>;
    report_id: number;
    review_status: string;
    reject_reason: string | null;
    memo: string | null;
    reflected_risk: Generated<number>;
    reviewed_by: number;
    reviewed_at: Generated<Timestamp>;
};
export type RiskCalculation = {
    id: Generated<number>;
    calculation_uid: string;
    trigger_type: string;
    trigger_report_id: number | null;
    triggered_by: number | null;
    rule_version: string;
    affected_beach_count: Generated<number>;
    calc_status: Generated<string>;
    error_message: string | null;
    started_at: Generated<Timestamp>;
    finished_at: Timestamp | null;
};
export type RiskFactor = {
    id: Generated<number>;
    risk_score_id: number;
    factor_code: string;
    factor_name: string;
    factor_detail: string | null;
    score_delta: number;
    source_report_id: number | null;
    display_order: Generated<number>;
};
export type RiskRecommendation = {
    id: Generated<number>;
    action_code: string;
    risk_level: string;
    title: string;
    description: string | null;
    display_order: Generated<number>;
    active: Generated<number>;
    created_at: Generated<Timestamp>;
    updated_at: Timestamp;
};
export type RiskRuleConfig = {
    id: Generated<number>;
    rule_code: string;
    rule_category: string;
    rule_name: string;
    score: number | null;
    condition_json: unknown | null;
    min_risk_level: string | null;
    version: Generated<string>;
    active: Generated<number>;
    updated_by: number | null;
    created_at: Generated<Timestamp>;
    updated_at: Timestamp;
};
export type RiskScore = {
    id: Generated<number>;
    calculation_id: number;
    beach_id: number;
    horizon: string;
    risk_score: number;
    risk_level: string;
    base_risk_level: string | null;
    min_level_applied: Generated<number>;
    min_level_rule_code: string | null;
    data_confidence: Generated<string>;
    rule_version: string;
    model_id: number | null;
    is_latest: number | null;
    generated_at: Generated<Timestamp>;
};
export type StaticGuide = {
    id: Generated<number>;
    guide_code: string;
    target_type: string;
    risk_level: string | null;
    title: string | null;
    body: string;
    display_order: Generated<number>;
    active: Generated<number>;
    created_at: Generated<Timestamp>;
    updated_at: Timestamp;
};
export type Subscription = {
    id: Generated<number>;
    user_id: number;
    subscriber_type: string;
    plan_code: string;
    subscription_status: Generated<string>;
    price_amount: string | null;
    payment_status: string | null;
    started_at: Timestamp | null;
    expires_at: Timestamp | null;
    created_at: Generated<Timestamp>;
};
export type SubscriptionArea = {
    id: Generated<number>;
    subscription_id: number;
    beach_id: number | null;
    label: string | null;
    center_lat: string | null;
    center_lng: string | null;
    radius_km: string | null;
    created_at: Generated<Timestamp>;
};
export type User = {
    id: Generated<number>;
    role: Generated<string>;
    email: string;
    password_hash: string;
    name: string;
    organization: string | null;
    managed_region: string | null;
    is_active: Generated<number>;
    last_login_at: Timestamp | null;
    created_at: Generated<Timestamp>;
    updated_at: Timestamp;
};
export type VisionResult = {
    id: Generated<number>;
    report_id: number;
    model_name: Generated<string>;
    model_version: string | null;
    result: string | null;
    confidence: string | null;
    process_status: Generated<string>;
    error_message: string | null;
    raw_response: unknown | null;
    is_latest: number | null;
    requested_at: Generated<Timestamp>;
    processed_at: Timestamp | null;
};
export type DB = {
    audit_logs: AuditLog;
    beaches: Beach;
    consent_logs: ConsentLog;
    daily_reports: DailyReport;
    data_sources: DataSource;
    favorite_beaches: FavoriteBeach;
    jellyfish_occurrences: JellyfishOccurrence;
    jellyfish_reports: JellyfishReport;
    ml_models: MlModel;
    notification_consents: NotificationConsent;
    notification_dispatches: NotificationDispatch;
    notification_templates: NotificationTemplate;
    notifications: Notification;
    observation_mappings: ObservationMapping;
    observation_stations: ObservationStation;
    observations: Observation;
    operation_actions: OperationAction;
    operation_status_logs: OperationStatusLog;
    partner_api_call_logs: PartnerApiCallLog;
    partner_api_keys: PartnerApiKey;
    partners: Partner;
    report_consents: ReportConsent;
    report_reviews: ReportReview;
    risk_calculations: RiskCalculation;
    risk_factors: RiskFactor;
    risk_recommendations: RiskRecommendation;
    risk_rule_configs: RiskRuleConfig;
    risk_scores: RiskScore;
    static_guides: StaticGuide;
    subscription_areas: SubscriptionArea;
    subscriptions: Subscription;
    users: User;
    vision_results: VisionResult;
};
